import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Offesive Gaming</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>

        
        <nav className={styles.nav}>
          <a href="/" className='site-title'>
          Offesive Gaming

          </a>
          <ul>
            <li>
            <a href="/Vision">Vision</a>
            </li>
             <li>
            <a href="/Culture">Culture</a>
            </li>
            <li>
            <a href="/Games">Games</a>
            </li>
            <li>
            <a href="/Turku">Turku</a>
            </li>
          
          
          
          </ul>
          
        </nav>

      </header>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Offesive Gaming
        </h1>

        <p className={styles.description}>
          Our Games. {' '}
          
        </p>

        <div className={styles.grid} >
        <h2>Orkki pely &rarr;</h2>
            <p></p>
          <a href="https://orkkypely.offensivegames.dy.fi/"  >
            <img src="peli.png" alt="peli" className={styles.card} />
            
          </a>

        
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
